version: '3'
services:
  php:
    build:
      context: .
    container_name: php_app
    ports:
      - 80:80
    environment: 
      - APACHE_DOCUMENT_ROOT=/var/www/html/symfony
    volumes: 
      - ./symfony:/var/www/html/symfony
      - ./docker/vhost.conf:/etc/apache2/sites-available/000-default.conf
  db:
    container_name: db
    image: mysql:5.6
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment: 
      MYSQL_ROOT_PASSWORD: root
      MYSQL_Database: resurgence
      MYSQL_USER: resurgence
      MYSQL_PASSWORD: 1234
    ports: 
      - 6033:3306
